### PR TITLE
some style changes

### PR DESCRIPTION
**Pull request by saulpw**
The idea is that the rankings page would be the only toplevel page, and it would be very simple. 

The Human and Consistency become part of a list of scores, and only the aggregate (average) is shown.  And there could be 1, 3, or any number of different prompts and their responses evaluated by GPT-4. 

I removed the individual scores since they're for similar prompts, but if the prompts were different, maybe the columns would come back, with the score headings linking to the prompt text maybe?

### CODE REVIEW

**Comment by cthulahoops** [comment]
I'll have a proper look at this tomorrow, I only had time to have a quick look. One thing I noticed is how much I use this view to spot more anomalies in the data - I can no longer see missing scores or weird outliers, for example.

Maybe we need a simpler table on the front page and still keep the full table somewhere else, or is there an in between view that's simpler but still shows me what I need?

Thank you for looking at this!

**Comment by saulpw** [comment]
> One thing I noticed is how much I use this view to spot more anomalies in the data - I can no longer see missing scores or weird outliers, for example.

I had N and Stdev columns at first, but decided to try a "minimal" approach as a first pass.  Could a visual indicator be added without the full matrix?  And the full matrix could still totally go on an expanded/dev page.

**Comment by cthulahoops** [comment]
Thinking about what I use the ranking table for:

* Seeing the top models.
* Looking at price vs performance.
* Spotting which models don't have evaluations, or incomplete evaluations.
* Finding outliers - solutions with very odd scores.
* Seeing the consistency helps here, because if the scores are inconsistent but the solutions aren't I know it's an evaluation problem.
* Human-like is probably the least important part of this table.

I miss the colours - they draw my eye!

I'm not sure I like turning the cost into a link.

Something is breaking the navigation layout on other pages - I'm guessing the max width needs to be set on main rather than body? (Not sure why a min-width is being set.) Were you thinking the model selection sidebar would go away when browsing generally?

Btw, I made really good progress on my refactoring and testing work this week. Hoping I'll be able to really get into the design thinking next week.

**Comment by saulpw** [comment]
That's fine, this is good for triggering discussion at least.  Don't worry about fixing or merging it, let's talk about it on Monday.

**Comment by cthulahoops** [comment]
So, following on from our conversation:

+ Github banner in a separate template on the main page only.
+ Colours are back!
+ Streamlined tables on the home page, and full rankings on the rankings page.
+ Highlight with box-shadows because it works better with the coloured cells.

I think this is now mergable and we can figure out the sidebar question later.

**Pull request merged**
